version: '3'

services:
  postgis:
    image: postgis/postgis:13-3.2
    environment:
      POSTGRES_PASSWORD: postgis
      POSTGRES_DB: postgis
      POSTGRES_USER: postgis
    ports:
      - 5431:5432