[package]
name = "sqlx_almanac"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
futures = "0.3"
sqlx = { version = "0.8.0", features = [ "runtime-async-std", "postgres", "chrono"] }
chrono = "0.4.38"